### ISSUE TITLE
more ideas

### ISSUE THREAD

**Issue by mattdesl** [tmcw/testing-webgl#3]
:+1: Great idea.

For local/interactive testing of WebGL/GLSL, I've been using [hihat](https://github.com/Jam3/hihat/). Since it's essentially just Electron and browserify, it should be possible to run on the server.

Some modules that have helped me with GLSL unit tests in the past:
- [gl-shader-output](https://github.com/Jam3/gl-shader-output)
- [glslify-testify](https://www.npmjs.com/package/glsl-testify)
- [webgl-compile-shader](https://github.com/mattdesl/webgl-compile-shader)

**Comment by tmcw** [comment]
Cool - I can add a section for local testing. The emphasis has been on CI testing, because that's been much harder to find solutions for.
