### ISSUE TITLE
Browserstack says they support WebGL on Win 8.1 too

### ISSUE THREAD

**Issue by tbroyer** [tmcw/testing-webgl#4]
See https://twitter.com/browserstack/status/502153784756162560, dating as far as 2014.
And it was advertized a bit earlier in an MSDN Blog: https://blogs.msdn.microsoft.com/uk_faculty_connection/2014/04/07/webgl-to-windows-8/

**Comment by tmcw** [comment]
Yep, it's under "sketchy/unconfirmed" - happy to shift it into "confirmed" if we can get a working proof of this compatibility, but given the wide gap between claims and reality I won't take browserstack on their word.

**Comment by tbroyer** [comment]
My comment wasn't much about whether browserstack should be in sketchy or confirmed (we'll have to test it soon, so I'll give feedback then), but that it's not only on OSX but also on Win 8.1.
